import type { CSSProperties } from 'react';

/** Shared embedded CSS for Cash Buyer + Hard Money directory pages. */
export const DIRECTORY_BASE_CSS = `
  @keyframes dgiq-toast-in { from { opacity: 0; transform: translateX(-50%) translateY(-12px); } to { opacity: 1; transform: translateX(-50%) translateY(0); } }
  .dgiq-directory-card { transition: border-color 0.2s, box-shadow 0.2s; }
  .dgiq-directory-card:hover { border-color: var(--border-strong); }
  .dgiq-input:focus, .dgiq-select:focus {
    outline: none;
    border-color: var(--border-focus) !important;
    box-shadow: 0 0 0 3px color-mix(in srgb, var(--accent-sky) 15%, transparent);
  }
  .dgiq-btn-press { transition: all 0.15s ease; }
  .dgiq-btn-press:active { transform: scale(0.97); }
`;

export const directoryTokens = {
  accent: 'var(--accent-sky)',
  accentOnAccent: 'var(--text-inverse)',
  heading: 'var(--text-heading)',
  body: 'var(--text-body)',
  secondary: 'var(--text-secondary)',
  label: 'var(--text-label)',
  muted: 'var(--text-muted)',
  link: 'var(--text-link)',
  border: 'var(--border-default)',
  borderSubtle: 'var(--border-subtle)',
  borderStrong: 'var(--border-strong)',
  surfaceCard: 'var(--surface-card)',
  surfaceElevated: 'var(--surface-elevated)',
  surfaceInput: 'var(--surface-input)',
  statusWarning: 'var(--status-warning)',
  shadowCard: 'var(--shadow-card)',
  shadowDropdown: 'var(--shadow-dropdown)',
} as const;

export const directoryBaseStyles = {
  page: {
    minHeight: '100vh',
    background: 'var(--surface-base)',
    color: 'var(--text-heading)',
    fontFamily: '"DM Sans", -apple-system, BlinkMacSystemFont, sans-serif',
    padding: '32px 24px 100px',
    position: 'relative',
  },
  container: { maxWidth: 1280, margin: '0 auto' },
  eyebrow: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 8,
    marginBottom: 14,
    fontSize: 11,
    color: 'var(--accent-sky)',
    letterSpacing: 2,
    textTransform: 'uppercase',
    fontFamily: 'Space Mono, monospace',
  },
  eyebrowDot: {
    width: 6,
    height: 6,
    borderRadius: '50%',
    background: 'var(--accent-sky)',
    boxShadow: '0 0 12px var(--accent-sky)',
  },
  h1: {
    fontSize: 'clamp(36px, 5vw, 52px)',
    fontWeight: 700,
    lineHeight: 1.05,
    margin: '0 0 14px',
    letterSpacing: '-0.02em',
  },
  sub: {
    fontSize: 17,
    color: 'var(--text-secondary)',
    maxWidth: 720,
    lineHeight: 1.5,
    margin: 0,
  },
  panel: {
    background: 'var(--surface-card)',
    border: '1px solid var(--border-default)',
    borderRadius: 14,
    padding: 20,
    marginBottom: 20,
  },
  fieldLabel: {
    display: 'block',
    fontFamily: 'Space Mono, monospace',
    fontSize: 10,
    color: 'var(--text-label)',
    letterSpacing: 1.4,
    textTransform: 'uppercase',
    marginBottom: 7,
  },
  input: {
    width: '100%',
    background: 'var(--surface-input)',
    color: 'var(--text-heading)',
    border: '1px solid var(--border-default)',
    borderRadius: 9,
    padding: '12px 14px 12px 42px',
    fontFamily: 'inherit',
    fontSize: 14,
    boxSizing: 'border-box',
    transition: 'all 0.2s',
  },
  select: {
    width: '100%',
    background: 'var(--surface-input)',
    color: 'var(--text-heading)',
    border: '1px solid var(--border-default)',
    borderRadius: 9,
    padding: '12px 14px',
    fontFamily: 'inherit',
    fontSize: 14,
    fontWeight: 600,
    cursor: 'pointer',
    appearance: 'none',
    backgroundImage: `url("data:image/svg+xml,%3Csvg width='10' height='6' viewBox='0 0 10 6' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M1 1l4 4 4-4' stroke='%2364748b' stroke-width='1.5' fill='none' stroke-linecap='round'/%3E%3C/svg%3E")`,
    backgroundRepeat: 'no-repeat',
    backgroundPosition: 'right 14px center',
  },
  filterRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    paddingTop: 16,
    borderTop: '1px solid var(--border-default)',
  },
  countStrip: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 18,
    padding: '0 4px',
    flexWrap: 'wrap',
    gap: 12,
  },
  countNum: {
    fontFamily: 'Space Mono, monospace',
    fontSize: 30,
    fontWeight: 700,
    color: 'var(--accent-sky)',
  },
  selectAllBtn: {
    background: 'transparent',
    color: 'var(--accent-sky)',
    border: '1px solid color-mix(in srgb, var(--accent-sky) 30%, transparent)',
    padding: '6px 12px',
    borderRadius: 7,
    cursor: 'pointer',
    fontFamily: 'inherit',
    fontSize: 12,
    fontWeight: 600,
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
  },
  card: {
    background: 'var(--surface-card)',
    border: '1px solid var(--border-subtle)',
    borderRadius: 14,
    padding: 18,
    position: 'relative',
    overflow: 'hidden',
  },
  cardDesc: {
    fontSize: 13,
    color: 'var(--text-body)',
    lineHeight: 1.55,
    margin: '0 0 14px',
  },
  miniLabel: {
    fontFamily: 'Space Mono, monospace',
    fontSize: 9,
    color: 'var(--text-label)',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    marginBottom: 6,
  },
  strategyChip: {
    background: 'color-mix(in srgb, var(--accent-sky) 10%, transparent)',
    color: 'var(--accent-sky)',
    padding: '2px 9px',
    borderRadius: 999,
    fontSize: 11,
    fontWeight: 600,
    border: '1px solid color-mix(in srgb, var(--accent-sky) 22%, transparent)',
  },
  emptyState: {
    gridColumn: '1 / -1',
    background: 'var(--surface-card)',
    border: '1px solid var(--border-default)',
    borderRadius: 14,
    padding: 24,
    color: 'var(--text-secondary)',
    fontSize: 14,
    textAlign: 'center',
  },
  gateWrap: {
    position: 'absolute',
    inset: 0,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 32,
    pointerEvents: 'auto',
  },
  gateCard: {
    maxWidth: 560,
    width: '100%',
    margin: '0 auto',
    background: 'var(--surface-card)',
    border: '1px solid color-mix(in srgb, var(--accent-sky) 40%, transparent)',
    borderRadius: 18,
    padding: 32,
    boxShadow: 'var(--shadow-dropdown)',
    textAlign: 'center',
  },
  gateIcon: {
    width: 52,
    height: 52,
    borderRadius: 13,
    margin: '0 auto 16px',
    background: 'linear-gradient(135deg, var(--accent-sky) 0%, var(--accent-brand-blue) 100%)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    boxShadow: '0 0 32px color-mix(in srgb, var(--accent-sky) 40%, transparent)',
  },
  gateEyebrow: {
    fontFamily: 'Space Mono, monospace',
    fontSize: 11,
    color: 'var(--accent-sky)',
    letterSpacing: 2,
    textTransform: 'uppercase',
    marginBottom: 8,
  },
  gateTitle: {
    fontSize: 24,
    fontWeight: 700,
    margin: '0 0 12px',
    letterSpacing: '-0.01em',
  },
  gateDesc: {
    fontSize: 14,
    color: 'var(--text-secondary)',
    lineHeight: 1.55,
    margin: '0 0 22px',
  },
  gateBtn: {
    width: '100%',
    background: 'var(--accent-sky)',
    color: 'var(--text-inverse)',
    border: 'none',
    padding: '13px 24px',
    borderRadius: 10,
    cursor: 'pointer',
    fontFamily: 'inherit',
    fontWeight: 700,
    fontSize: 14,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  statCell: {
    background: 'var(--surface-elevated)',
    padding: '8px 10px',
    borderRadius: 7,
  },
  statValue: {
    fontFamily: 'Space Mono, monospace',
    fontSize: 12,
    fontWeight: 700,
    color: 'var(--text-heading)',
    letterSpacing: '-0.02em',
    marginTop: 2,
  },
  statLabel: {
    fontFamily: 'Space Mono, monospace',
    fontSize: 9,
    color: 'var(--text-label)',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
  },
  contactRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 7,
    padding: '2px 0',
    fontSize: 12,
    color: 'var(--text-body)',
  },
  gateFeatureRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    fontSize: 14,
    color: 'var(--text-body)',
  },
  mutedTextSm: { fontSize: 12, color: 'var(--text-secondary)' },
  mutedTextMd: { fontSize: 14, color: 'var(--text-secondary)' },
  footnoteText: { fontSize: 12, color: 'var(--text-muted)' },
  paidProBadge: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    fontSize: 12,
    color: 'var(--status-warning)',
  },
  fieldIcon: {
    position: 'absolute',
    left: 14,
    top: '50%',
    transform: 'translateY(-50%)',
    color: 'var(--text-muted)',
    pointerEvents: 'none',
  },
} as Record<string, CSSProperties>;
