#!/usr/bin/env bash
# DealGapIQ Cloud Agent — one-time environment bootstrap.
#
# Idempotent: safe to re-run. Installs system packages (Postgres, Redis,
# WeasyPrint's native libs), the Python 3.11 backend venv (matching CI and
# pyproject's requires-python), and the frontend workspace dependencies.
#
# Per-boot service startup and DB migrations live in start.sh, not here.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

echo "==> Installing system packages (Postgres, Redis, WeasyPrint libs)"
sudo apt-get update -y
sudo DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
  postgresql postgresql-contrib \
  redis-server \
  libcairo2 libpango-1.0-0 libpangocairo-1.0-0 libgdk-pixbuf-2.0-0 \
  libffi8 libjpeg-turbo8 shared-mime-info fonts-dejavu-core

echo "==> Ensuring uv is installed (manages the Python 3.11 interpreter)"
export PATH="$HOME/.local/bin:$PATH"
if ! command -v uv >/dev/null 2>&1; then
  pip install --user --break-system-packages uv || pip install --user uv
fi

echo "==> Creating backend virtualenv (Python 3.11) and installing requirements"
cd "$REPO_ROOT/backend"
if [ ! -x .venv/bin/python ]; then
  uv venv --python 3.11 --seed .venv
fi
uv pip install --python .venv/bin/python -r requirements.txt

echo "==> Writing backend/.env for local dev (only if absent)"
if [ ! -f .env ]; then
  SECRET_KEY="$(.venv/bin/python -c 'import secrets; print(secrets.token_hex(32))')"
  cat > .env <<ENV
# Local development environment for DealGapIQ backend (Cloud Agent).
# Generated by .cursor/install.sh — dev only, not for production.
# Kept minimal so the backend test suite (which loads this .env) sees the
# same feature-flag defaults as CI. conftest.py overrides ENVIRONMENT,
# SECRET_KEY, and DATABASE_URL via os.environ under pytest.
ENVIRONMENT=development
SECRET_KEY=${SECRET_KEY}
DATABASE_URL=postgresql://postgres:postgres@localhost:5432/dealgapiq
REDIS_URL=redis://localhost:6379/0
# External data-provider keys are secrets; add them as Cloud Agent secrets to
# enable live property search: RENTCAST_API_KEY, AXESSO_API_KEY,
# REDFIN_API_KEY, REALTOR_API_KEY.
ENV
fi

echo "==> Installing frontend workspace dependencies (npm ci at repo root)"
cd "$REPO_ROOT"
npm ci

echo "==> install.sh complete"
