"""
DealGapIQ Appraisal Report — PDF Generator

Generates a professional, multi-page appraisal-style report from
user-selected comps and the derived ARV. Uses WeasyPrint (HTML → PDF)
following the same architecture as property_report_pdf.py.

Report pages:
  1. Cover — subject property details
  2. Comparable Sales Adjustment Grid — the core appraisal artifact
  3. Value Reconciliation & ARV — methodology breakdown
  4. Disclaimer & Methodology notes
"""

import logging
from datetime import datetime
from io import BytesIO

from app.schemas.appraisal_report import AppraisalReportRequest
from app.services.pdf_chart_helpers import get_palette
from app.services.property_report_pdf import _ensure_weasyprint

logger = logging.getLogger(__name__)


def _fmt(val: float, decimals: int = 0) -> str:
    if decimals == 0:
        return f"{val:,.0f}"
    return f"{val:,.{decimals}f}"


def _fmt_money(val: float) -> str:
    return f"${val:,.0f}"


def _fmt_pct(val: float, decimals: int = 1) -> str:
    return f"{val:.{decimals}f}%"


def _sign_money(val: float) -> str:
    if val >= 0:
        return f"+${val:,.0f}"
    return f"-${abs(val):,.0f}"


class AppraisalReportPDFExporter:
    """Generate a professional appraisal-style PDF from selected comps."""

    def __init__(self, data: AppraisalReportRequest):
        self.data = data
        self.theme = data.theme if data.theme in ("light", "dark") else "light"
        self.palette = get_palette(self.theme)
        self.now = datetime.now()

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def generate(self) -> BytesIO:
        """Render the full PDF via WeasyPrint and return as BytesIO."""
        HTML, CSS = _ensure_weasyprint()

        html_content = self._build_html()
        css_content = self._build_css()

        html = HTML(string=html_content)
        css = CSS(string=css_content)

        buffer = BytesIO()
        html.write_pdf(buffer, stylesheets=[css])
        buffer.seek(0)
        return buffer

    def generate_html(self, auto_print: bool = True) -> str:
        """Return self-contained HTML for browser print-to-PDF (no WeasyPrint)."""
        css_content = self._build_css()
        body_content = self._build_body()

        print_script = ""
        if auto_print:
            print_script = """
<script>
  document.fonts.ready.then(function() {
    setTimeout(function() { window.print(); }, 400);
  });
</script>"""

        address = self.data.subject_address
        return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>DealGapIQ Appraisal Report — {address}</title>
<style>{css_content}</style>
{print_script}
</head>
<body>
{body_content}
</body>
</html>"""

    # ------------------------------------------------------------------
    # HTML assembly
    # ------------------------------------------------------------------

    def _build_body(self) -> str:
        return f"""{self._page_cover()}
{self._page_adjustments()}
{self._page_reconciliation()}
{self._page_disclaimer()}"""

    def _build_html(self) -> str:
        return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>DealGapIQ Appraisal Report — {self.data.subject_address}</title>
</head>
<body>
{self._build_body()}
</body>
</html>"""

    # ------------------------------------------------------------------
    # Reusable layout helpers
    # ------------------------------------------------------------------

    def _page_header(self, title: str) -> str:
        parts = self.data.subject_address.split(",")
        city_state = ", ".join(parts[1:]).strip() if len(parts) > 1 else ""
        return (
            f'<div class="page-header">'
            f'<div class="logo">DealGap<span class="logo-iq">IQ</span></div>'
            f'<div class="page-header-title">{title}</div>'
            f'<div class="page-header-meta">{city_state}</div>'
            f"</div>"
        )

    def _page_footer(self) -> str:
        return (
            f'<div class="page-footer">'
            f'<div class="footer-brand">Generated by DealGapIQ</div>'
            f'<div class="footer-date">{self.now.strftime("%B %d, %Y")}</div>'
            f"</div>"
        )

    def _section_header(self, label: str, title: str) -> str:
        return (
            f'<div class="section-header">'
            f'<div class="section-label">{label}</div>'
            f'<h2 class="section-title">{title}</h2>'
            f'<div class="section-rule"></div>'
            f"</div>"
        )

    def _info_card(self, icon: str, label: str, value: str, sub: str = "") -> str:
        sub_html = f'<div class="info-card-sub">{sub}</div>' if sub else ""
        return (
            f'<div class="info-card">'
            f'<div class="info-card-icon">{icon}</div>'
            f'<div class="info-card-label">{label}</div>'
            f'<div class="info-card-value">{value}</div>'
            f"{sub_html}"
            f"</div>"
        )

    # ------------------------------------------------------------------
    # Page 1: Cover
    # ------------------------------------------------------------------

    def _page_cover(self) -> str:
        d = self.data
        parts = d.subject_address.split(",")
        street = parts[0].strip() if parts else d.subject_address
        city_state = ", ".join(parts[1:]).strip() if len(parts) > 1 else ""

        lot_display = f"{d.subject_lot_size:,.0f} sqft" if d.subject_lot_size >= 1000 else f"{d.subject_lot_size:.2f} acres"
        list_price_html = f'<div class="cover-stat"><div class="cover-stat-icon">&#x1F4B0;</div><div class="cover-stat-value">{_fmt_money(d.list_price)}</div><div class="cover-stat-label">List Price</div></div>' if d.list_price else ""
        rehab_html = f'<div class="cover-stat"><div class="cover-stat-icon">&#x1F6E0;</div><div class="cover-stat-value">{_fmt_money(d.rehab_cost)}</div><div class="cover-stat-label">Est. Rehab</div></div>' if d.rehab_cost and d.rehab_cost > 0 else ""

        return f"""
<div class="page cover-page">
  <div class="cover-top-band"></div>
  <div class="cover-content">
    <div class="cover-logo">DealGap<span class="logo-iq">IQ</span></div>
    <div class="cover-badge">Comparable Sales Appraisal Report</div>
    <h1 class="cover-address">{street}</h1>
    <div class="cover-city">{city_state}</div>

    <div class="cover-stats">
      <div class="cover-stat">
        <div class="cover-stat-icon">&#x1F3E0;</div>
        <div class="cover-stat-value">{d.subject_beds}</div>
        <div class="cover-stat-label">Bedrooms</div>
      </div>
      <div class="cover-stat">
        <div class="cover-stat-icon">&#x1F6C1;</div>
        <div class="cover-stat-value">{d.subject_baths}</div>
        <div class="cover-stat-label">Bathrooms</div>
      </div>
      <div class="cover-stat">
        <div class="cover-stat-icon">&#x1F4CF;</div>
        <div class="cover-stat-value">{_fmt(d.subject_sqft)}</div>
        <div class="cover-stat-label">Sq Ft</div>
      </div>
      <div class="cover-stat">
        <div class="cover-stat-icon">&#x1F3D7;</div>
        <div class="cover-stat-value">{d.subject_year_built}</div>
        <div class="cover-stat-label">Year Built</div>
      </div>
      <div class="cover-stat">
        <div class="cover-stat-icon">&#x1F333;</div>
        <div class="cover-stat-value">{lot_display}</div>
        <div class="cover-stat-label">Lot Size</div>
      </div>
      {list_price_html}
      {rehab_html}
    </div>

    <div class="cover-summary-cards">
      <div class="cover-value-card">
        <div class="cover-value-label">Market Value (As-Is)</div>
        <div class="cover-value-amount">{_fmt_money(d.market_value)}</div>
        <div class="cover-value-range">Range: {_fmt_money(d.range_low)} — {_fmt_money(d.range_high)}</div>
      </div>
      <div class="cover-value-card cover-value-card-arv">
        <div class="cover-value-label">After Repair Value (ARV)</div>
        <div class="cover-value-amount">{_fmt_money(d.arv)}</div>
        <div class="cover-value-range">Confidence: {d.confidence:.0f}%</div>
      </div>
    </div>

    <p class="narrative">
      This report presents a comparable sales analysis for {street}{(", " + city_state) if city_state else ""}.
      {len(d.comp_adjustments)} comparable properties were selected and adjusted to derive a
      market value estimate of {_fmt_money(d.market_value)} and an After Repair Value (ARV)
      of {_fmt_money(d.arv)} with a confidence score of {d.confidence:.0f}%.
    </p>
  </div>

  <div class="cover-footer">
    <div class="cover-footer-left">
      <span class="cover-footer-label">Report Date</span>
      <span class="cover-footer-value">{self.now.strftime("%B %d, %Y")}</span>
    </div>
    <div class="cover-footer-right">
      <span class="cover-footer-label">Comps Analyzed</span>
      <span class="cover-footer-value">{len(d.comp_adjustments)} comparable sales</span>
    </div>
  </div>
</div>"""

    # ------------------------------------------------------------------
    # Page 2: Comparable Sales Adjustment Grid
    # ------------------------------------------------------------------

    def _page_adjustments(self) -> str:
        d = self.data
        p = self.palette
        comps = d.comp_adjustments

        if not comps:
            return ""

        # Subject column header
        subj_header = (
            f"<th>Subject</th>"
        )
        comp_headers = "".join(
            f"<th>Comp {i + 1}</th>" for i in range(len(comps))
        )

        def _adj_cell(val: float) -> str:
            color = p["positive"] if val >= 0 else p["negative"]
            return f'<td class="money" style="color:{color}">{_sign_money(val)}</td>'

        # Build rows
        # Address
        subj_addr_parts = d.subject_address.split(",")
        subj_street = subj_addr_parts[0].strip()
        addr_row = f"<tr><td class='row-label'>Address</td><td>{subj_street}</td>"
        for c in comps:
            addr_parts = c.comp_address.split(",")
            addr_row += f"<td>{addr_parts[0].strip()}</td>"
        addr_row += "</tr>"

        # Sale Price
        price_row = f"<tr><td class='row-label'>Sale Price</td><td>—</td>"
        for c in comps:
            price_row += f'<td class="money">{_fmt_money(c.base_price)}</td>'
        price_row += "</tr>"

        # Beds
        beds_row = f"<tr><td class='row-label'>Bedrooms</td><td>{d.subject_beds}</td>"
        for c in comps:
            beds_row += f"<td>{c.beds}</td>"
        beds_row += "</tr>"

        # Baths
        baths_row = f"<tr><td class='row-label'>Bathrooms</td><td>{d.subject_baths}</td>"
        for c in comps:
            baths_row += f"<td>{c.baths}</td>"
        baths_row += "</tr>"

        # Sqft
        sqft_row = f"<tr><td class='row-label'>Sq Ft</td><td>{_fmt(d.subject_sqft)}</td>"
        for c in comps:
            sqft_row += f"<td>{_fmt(c.sqft)}</td>"
        sqft_row += "</tr>"

        # Year Built
        year_row = f"<tr><td class='row-label'>Year Built</td><td>{d.subject_year_built}</td>"
        for c in comps:
            year_row += f"<td>{c.year_built}</td>"
        year_row += "</tr>"

        # Sale Date
        date_row = f"<tr><td class='row-label'>Sale Date</td><td>—</td>"
        for c in comps:
            date_row += f"<td>{c.sale_date or '—'}</td>"
        date_row += "</tr>"

        # Distance
        dist_row = f"<tr><td class='row-label'>Distance</td><td>—</td>"
        for c in comps:
            dist_row += f"<td>{c.distance_miles:.1f} mi</td>" if c.distance_miles is not None else "<td>—</td>"
        dist_row += "</tr>"

        # $/Sqft
        ppsf_row = f"<tr><td class='row-label'>$/Sq Ft</td><td>—</td>"
        for c in comps:
            ppsf_row += f'<td class="money">${c.price_per_sqft:,.0f}</td>'
        ppsf_row += "</tr>"

        # Adjustments section header
        adj_section = f'<tr class="adj-header"><td class="row-label" colspan="{len(comps) + 2}">Adjustments</td></tr>'

        # Size adj
        size_row = f"<tr><td class='row-label adj-label'>Size</td><td>—</td>"
        for c in comps:
            size_row += _adj_cell(c.size_adjustment)
        size_row += "</tr>"

        # Bedroom adj
        bed_row = f"<tr><td class='row-label adj-label'>Bedroom</td><td>—</td>"
        for c in comps:
            bed_row += _adj_cell(c.bedroom_adjustment)
        bed_row += "</tr>"

        # Bathroom adj
        bath_adj_row = f"<tr><td class='row-label adj-label'>Bathroom</td><td>—</td>"
        for c in comps:
            bath_adj_row += _adj_cell(c.bathroom_adjustment)
        bath_adj_row += "</tr>"

        # Age adj
        age_row = f"<tr><td class='row-label adj-label'>Age</td><td>—</td>"
        for c in comps:
            age_row += _adj_cell(c.age_adjustment)
        age_row += "</tr>"

        # Lot adj
        lot_row = f"<tr><td class='row-label adj-label'>Lot</td><td>—</td>"
        for c in comps:
            lot_row += _adj_cell(c.lot_adjustment)
        lot_row += "</tr>"

        # Total adj
        total_adj_row = f'<tr class="total-row"><td class="row-label">Total Adjustment</td><td>—</td>'
        for c in comps:
            total_adj_row += _adj_cell(c.total_adjustment)
        total_adj_row += "</tr>"

        # Adjusted price
        adjusted_row = f'<tr class="total-row"><td class="row-label">Adjusted Price</td><td>—</td>'
        for c in comps:
            adjusted_row += f'<td class="money" style="font-weight:700;">{_fmt_money(c.adjusted_price)}</td>'
        adjusted_row += "</tr>"

        # Similarity
        sim_row = f"<tr><td class='row-label'>Similarity</td><td>—</td>"
        for c in comps:
            color = p["positive"] if c.similarity_score >= 80 else (p["warning"] if c.similarity_score >= 60 else p["negative"])
            sim_row += f'<td style="color:{color};font-weight:600;">{c.similarity_score:.0f}%</td>'
        sim_row += "</tr>"

        # Weight
        wt_row = f"<tr><td class='row-label'>Weight</td><td>—</td>"
        for c in comps:
            wt_row += f'<td style="font-weight:600;">{c.weight * 100:.1f}%</td>'
        wt_row += "</tr>"

        return f"""
<div class="page">
  {self._page_header("Comparable Sales Analysis")}
  {self._section_header("ADJUSTMENT GRID", "Comparable Sales Adjustment Grid")}

  <p class="narrative">
    Each comparable is adjusted to account for differences from the subject property.
    Positive adjustments indicate the comparable is inferior (subject is worth more);
    negative adjustments indicate the comparable is superior.
  </p>

  <table class="adj-table">
    <thead>
      <tr>
        <th class="row-label-header">Feature</th>
        {subj_header}
        {comp_headers}
      </tr>
    </thead>
    <tbody>
      {addr_row}
      {price_row}
      {beds_row}
      {baths_row}
      {sqft_row}
      {year_row}
      {date_row}
      {dist_row}
      {ppsf_row}
      {adj_section}
      {size_row}
      {bed_row}
      {bath_adj_row}
      {age_row}
      {lot_row}
      {total_adj_row}
      {adjusted_row}
      {sim_row}
      {wt_row}
    </tbody>
  </table>

  {self._page_footer()}
</div>"""

    # ------------------------------------------------------------------
    # Page 3: Value Reconciliation & ARV
    # ------------------------------------------------------------------

    def _page_reconciliation(self) -> str:
        d = self.data
        p = self.palette

        rehab_section = ""
        if d.rehab_cost and d.rehab_cost > 0:
            rehab_premium = d.arv - d.market_value
            rehab_section = f"""
      <div class="detail-row">
        <span>Estimated Rehab Cost</span>
        <span class="detail-value">{_fmt_money(d.rehab_cost)}</span>
      </div>
      <div class="detail-row">
        <span>Rehab Premium (15%)</span>
        <span class="detail-value" style="color:{p["positive"]}">{_fmt_money(rehab_premium)}</span>
      </div>"""
        else:
            rehab_section = f"""
      <div class="detail-row">
        <span>Appreciation Premium (15%)</span>
        <span class="detail-value" style="color:{p["positive"]}">{_fmt_money(d.arv - d.market_value)}</span>
      </div>"""

        conf_color = p["positive"] if d.confidence >= 80 else (p["warning"] if d.confidence >= 60 else p["negative"])
        conf_label = "HIGH" if d.confidence >= 80 else ("MODERATE" if d.confidence >= 60 else "LOW")

        return f"""
<div class="page">
  {self._page_header("Value Reconciliation")}
  {self._section_header("VALUE ANALYSIS", "Value Reconciliation & ARV")}

  <p class="narrative">
    The market value is derived using a weighted hybrid methodology that combines
    three approaches: the adjusted price method (40%), the price-per-square-foot
    method (40%), and a blended average of both (20%). Comparable properties are
    weighted by their similarity to the subject property.
  </p>

  <div class="grid-2" style="margin-top:24px;">
    <div>
      <div class="card">
        <h3 class="card-title">Valuation Methods</h3>
        <div class="detail-row">
          <span>Adjusted Price Method (40%)</span>
          <span class="detail-value">{_fmt_money(d.adjusted_price_value)}</span>
        </div>
        <div class="detail-row">
          <span>Price/Sqft Method (40%)</span>
          <span class="detail-value">{_fmt_money(d.price_per_sqft_value)}</span>
        </div>
        <div class="detail-row">
          <span>Blended Average (20%)</span>
          <span class="detail-value">{_fmt_money((d.adjusted_price_value + d.price_per_sqft_value) / 2)}</span>
        </div>
        <div class="detail-row" style="border-top:2px solid {p["border"]};padding-top:10px;font-weight:700;">
          <span>Weighted Avg $/Sqft</span>
          <span class="detail-value">${d.weighted_average_ppsf:,.0f}/sqft</span>
        </div>
      </div>

      <div class="card" style="margin-top:16px;">
        <h3 class="card-title">Confidence Assessment</h3>
        <div style="display:flex;align-items:center;gap:12px;margin-bottom:12px;">
          <div class="conf-ring" style="border-color:{conf_color};">
            <span class="conf-ring-value" style="color:{conf_color};">{d.confidence:.0f}%</span>
          </div>
          <div>
            <div style="font-weight:700;color:{conf_color};font-size:13px;">{conf_label} CONFIDENCE</div>
            <div style="font-size:10px;color:{p["text_secondary"]};">Based on {len(d.comp_adjustments)} comps analyzed</div>
          </div>
        </div>
        <div class="detail-row">
          <span>Comps Used</span>
          <span class="detail-value">{len(d.comp_adjustments)}</span>
        </div>
        <div class="detail-row">
          <span>Avg Similarity</span>
          <span class="detail-value">{sum(c.similarity_score for c in d.comp_adjustments) / max(len(d.comp_adjustments), 1):.0f}%</span>
        </div>
      </div>
    </div>

    <div>
      <div class="hero-card">
        <div class="hero-card-label">Market Value (As-Is)</div>
        <div class="hero-card-value">{_fmt_money(d.market_value)}</div>
        <div class="hero-card-sub">Range: {_fmt_money(d.range_low)} — {_fmt_money(d.range_high)}</div>
      </div>

      <div class="card" style="margin-top:16px;">
        <h3 class="card-title">ARV Derivation</h3>
        <div class="detail-row">
          <span>Market Value (As-Is)</span>
          <span class="detail-value">{_fmt_money(d.market_value)}</span>
        </div>
        {rehab_section}
        <div class="detail-row" style="border-top:2px solid {p["border"]};padding-top:10px;font-weight:700;">
          <span>After Repair Value (ARV)</span>
          <span class="detail-value" style="color:{p["brand"]};font-size:16px;">{_fmt_money(d.arv)}</span>
        </div>
      </div>

      <div class="callout-box" style="margin-top:16px;">
        <strong>Methodology:</strong> The hybrid approach reduces bias from any single
        valuation method. Similarity-based weighting ensures that the most comparable
        properties have the greatest influence on the final value estimate.
      </div>
    </div>
  </div>

  {self._page_footer()}
</div>"""

    # ------------------------------------------------------------------
    # Page 4: Disclaimer & Methodology
    # ------------------------------------------------------------------

    def _page_disclaimer(self) -> str:
        d = self.data
        comps = d.comp_adjustments

        comp_summary_rows = ""
        for i, c in enumerate(comps):
            parts = c.comp_address.split(",")
            short_addr = parts[0].strip()
            comp_summary_rows += (
                f"<tr>"
                f'<td style="font-weight:600;">Comp {i + 1}</td>'
                f"<td>{short_addr}</td>"
                f'<td class="money">{_fmt_money(c.base_price)}</td>'
                f'<td class="money">{_fmt_money(c.adjusted_price)}</td>'
                f"<td>{c.similarity_score:.0f}%</td>"
                f"<td>{c.weight * 100:.1f}%</td>"
                f"</tr>"
            )

        return f"""
<div class="page">
  {self._page_header("Methodology & Disclaimer")}
  {self._section_header("METHODOLOGY", "Appraisal Methodology & Sources")}

  <div class="card" style="margin-top:16px;">
    <h3 class="card-title">Comp Summary</h3>
    <table class="summary-table">
      <thead>
        <tr>
          <th></th><th>Address</th><th>Sale Price</th><th>Adj. Price</th><th>Similarity</th><th>Weight</th>
        </tr>
      </thead>
      <tbody>
        {comp_summary_rows}
      </tbody>
    </table>
  </div>

  <div class="grid-2" style="margin-top:20px;">
    <div class="card">
      <h3 class="card-title">Adjustment Factors</h3>
      <div class="detail-row">
        <span>Size (per sqft difference)</span>
        <span class="detail-value">$100</span>
      </div>
      <div class="detail-row">
        <span>Bedroom (per bedroom)</span>
        <span class="detail-value">$15,000</span>
      </div>
      <div class="detail-row">
        <span>Bathroom (per bathroom)</span>
        <span class="detail-value">$10,000</span>
      </div>
      <div class="detail-row">
        <span>Age (per year difference)</span>
        <span class="detail-value">$1,500</span>
      </div>
      <div class="detail-row">
        <span>Lot (per acre difference)</span>
        <span class="detail-value">$25,000</span>
      </div>
    </div>

    <div class="card">
      <h3 class="card-title">Weighting Methodology</h3>
      <div class="detail-row">
        <span>Adjusted Price Method</span>
        <span class="detail-value">40%</span>
      </div>
      <div class="detail-row">
        <span>Price/Sqft Method</span>
        <span class="detail-value">40%</span>
      </div>
      <div class="detail-row">
        <span>Hybrid Blend</span>
        <span class="detail-value">20%</span>
      </div>
      <div class="detail-row" style="border-top:1px solid {self.palette["border"]};padding-top:8px;">
        <span>Similarity Scoring</span>
        <span class="detail-value">Weighted</span>
      </div>
      <p style="font-size:9px;color:{self.palette["text_tertiary"]};margin-top:8px;line-height:1.5;">
        Location 25% · Size 25% · Bed/Bath 20% · Age 15% · Lot 15%
      </p>
    </div>
  </div>

  <div class="disclaimer">
    <strong>Important Disclaimer:</strong> This report is generated by DealGapIQ for
    investment analysis purposes only. It is <strong>not</strong> a licensed appraisal,
    BPO (Broker Price Opinion), or CMA prepared by a licensed appraiser. The values
    presented are estimates based on available comparable sales data and standardized
    adjustment factors. Actual property values may differ based on condition, features,
    market conditions, and other factors not captured in this analysis. This report
    should not be used as a substitute for a professional appraisal. Consult with a
    licensed appraiser and qualified real estate professionals before making investment
    decisions.
  </div>

  <div class="final-footer">
    <div class="logo" style="font-size:18px;">DealGap<span class="logo-iq">IQ</span></div>
    <div class="footer-date">Report generated {self.now.strftime("%B %d, %Y at %I:%M %p")}</div>
  </div>
</div>"""

    # ------------------------------------------------------------------
    # CSS
    # ------------------------------------------------------------------

    def _build_css(self) -> str:
        p = self.palette
        is_dark = self.theme == "dark"

        hero_gradient = (
            f"linear-gradient(135deg, {p['brand']} 0%, #0284c7 100%)"
            if not is_dark
            else "linear-gradient(135deg, #0C1220 0%, #1E293B 100%)"
        )
        hero_border = "none" if not is_dark else f"1px solid {p['brand']}40"

        return f"""
@page {{
    size: letter;
    margin: 0;
}}

@font-face {{
    font-family: 'Inter';
    src: url('https://fonts.gstatic.com/s/inter/v18/UcCO3FwrK3iLTeHuS_nVMrMxCp50SjIw2boKoduKmMEVuLyfMZg.ttf') format('truetype');
    font-weight: 400;
}}
@font-face {{
    font-family: 'Inter';
    src: url('https://fonts.gstatic.com/s/inter/v18/UcCO3FwrK3iLTeHuS_nVMrMxCp50SjIw2boKoduKmMEVuI6fMZg.ttf') format('truetype');
    font-weight: 600;
}}
@font-face {{
    font-family: 'Inter';
    src: url('https://fonts.gstatic.com/s/inter/v18/UcCO3FwrK3iLTeHuS_nVMrMxCp50SjIw2boKoduKmMEVuFuYMZg.ttf') format('truetype');
    font-weight: 700;
}}

* {{
    box-sizing: border-box;
    margin: 0;
    padding: 0;
}}

body {{
    font-family: 'Inter', 'Helvetica Neue', Arial, sans-serif;
    font-size: 11px;
    line-height: 1.5;
    color: {p["text_primary"]};
    background: {p["bg"]};
}}

.page {{
    width: 8.5in;
    min-height: 11in;
    padding: 0.6in 0.65in;
    page-break-after: always;
    position: relative;
    background: {p["bg"]};
}}

.page:last-child {{
    page-break-after: auto;
}}

/* ===== COVER ===== */

.cover-page {{
    display: flex;
    flex-direction: column;
    padding: 0;
}}

.cover-top-band {{
    height: 8px;
    background: linear-gradient(90deg, {p["brand"]}, {"#0284c7" if not is_dark else "#2DD4BF"});
}}

.cover-content {{
    flex: 1;
    padding: 50px 60px 30px;
    display: flex;
    flex-direction: column;
}}

.cover-logo {{
    font-size: 28px;
    font-weight: 700;
    color: {p["text_primary"]};
    margin-bottom: 32px;
}}

.cover-badge {{
    display: inline-block;
    padding: 5px 16px;
    border-radius: 100px;
    font-size: 11px;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 0.08em;
    color: {p["brand"]};
    background: {p["brand"]}15;
    border: 1px solid {p["brand"]}30;
    margin-bottom: 16px;
    align-self: flex-start;
}}

.cover-address {{
    font-size: 32px;
    font-weight: 700;
    color: {p["text_primary"]};
    line-height: 1.1;
    margin-bottom: 6px;
}}

.cover-city {{
    font-size: 15px;
    color: {p["text_secondary"]};
    margin-bottom: 28px;
}}

.cover-stats {{
    display: flex;
    gap: 24px;
    margin-bottom: 28px;
    padding: 20px 0;
    border-top: 1px solid {p["border"]};
    border-bottom: 1px solid {p["border"]};
    flex-wrap: wrap;
}}

.cover-stat {{
    text-align: center;
}}

.cover-stat-icon {{
    font-size: 18px;
    margin-bottom: 4px;
}}

.cover-stat-value {{
    font-size: 18px;
    font-weight: 700;
    color: {p["text_primary"]};
    font-variant-numeric: tabular-nums;
}}

.cover-stat-label {{
    font-size: 9px;
    font-weight: 600;
    color: {p["text_tertiary"]};
    text-transform: uppercase;
    letter-spacing: 0.04em;
    margin-top: 2px;
}}

.cover-summary-cards {{
    display: flex;
    gap: 16px;
    margin-bottom: 24px;
}}

.cover-value-card {{
    flex: 1;
    background: {p["card_bg"]};
    border: 1px solid {p["border"]};
    border-radius: 10px;
    padding: 16px;
    text-align: center;
    border-top: 3px solid {p["text_secondary"]};
}}

.cover-value-card-arv {{
    border-top-color: {p["brand"]};
}}

.cover-value-label {{
    font-size: 10px;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 0.06em;
    color: {p["text_tertiary"]};
    margin-bottom: 4px;
}}

.cover-value-amount {{
    font-size: 24px;
    font-weight: 700;
    color: {p["text_primary"]};
    font-variant-numeric: tabular-nums;
    margin-bottom: 4px;
}}

.cover-value-range {{
    font-size: 10px;
    color: {p["text_tertiary"]};
}}

.cover-footer {{
    display: flex;
    justify-content: space-between;
    padding: 20px 60px;
    border-top: 1px solid {p["border"]};
}}

.cover-footer-label {{
    font-size: 9px;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 0.06em;
    color: {p["text_tertiary"]};
    display: block;
    margin-bottom: 2px;
}}

.cover-footer-value {{
    font-size: 11px;
    font-weight: 600;
    color: {p["text_secondary"]};
}}

/* ===== PAGE HEADER / FOOTER ===== */

.page-header {{
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding-bottom: 12px;
    border-bottom: 2px solid {p["brand"]};
    margin-bottom: 24px;
}}

.page-header-title {{
    font-size: 12px;
    font-weight: 700;
    color: {p["text_secondary"]};
    text-transform: uppercase;
    letter-spacing: 0.06em;
}}

.page-header-meta {{
    font-size: 10px;
    color: {p["text_tertiary"]};
}}

.logo {{
    font-size: 16px;
    font-weight: 700;
    color: {p["text_primary"]};
}}

.logo-iq {{
    color: {p["brand"]};
}}

.page-footer {{
    position: absolute;
    bottom: 0.5in;
    left: 0.65in;
    right: 0.65in;
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding-top: 10px;
    border-top: 1px solid {p["border"]};
}}

.footer-brand {{
    font-size: 9px;
    font-weight: 600;
    color: {p["text_tertiary"]};
}}

.footer-date {{
    font-size: 9px;
    color: {p["text_tertiary"]};
}}

/* ===== SECTION HEADER ===== */

.section-header {{
    margin-bottom: 16px;
}}

.section-label {{
    font-size: 10px;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 0.1em;
    color: {p["brand"]};
    margin-bottom: 4px;
}}

.section-title {{
    font-size: 20px;
    font-weight: 700;
    color: {p["text_primary"]};
    margin-bottom: 8px;
}}

.section-rule {{
    width: 48px;
    height: 3px;
    background: {p["brand"]};
    border-radius: 2px;
}}

/* ===== GRIDS ===== */

.grid-2 {{
    display: flex;
    gap: 20px;
}}

.grid-2 > * {{
    flex: 1;
}}

/* ===== CARDS ===== */

.card {{
    background: {p["card_bg"]};
    border: 1px solid {p["border"]};
    border-radius: 10px;
    padding: 18px;
}}

.card-title {{
    font-size: 12px;
    font-weight: 700;
    color: {p["text_primary"]};
    margin-bottom: 12px;
}}

/* ===== INFO CARD ===== */

.info-card {{
    background: {p["card_bg"]};
    border: 1px solid {p["border"]};
    border-radius: 10px;
    padding: 16px;
    text-align: center;
    border-top: 3px solid {p["brand"]};
}}

.info-card-icon {{ font-size: 18px; margin-bottom: 6px; }}
.info-card-label {{ font-size: 9px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.06em; color: {p["text_tertiary"]}; margin-bottom: 4px; }}
.info-card-value {{ font-size: 18px; font-weight: 700; color: {p["text_primary"]}; font-variant-numeric: tabular-nums; }}
.info-card-sub {{ font-size: 10px; color: {p["text_tertiary"]}; margin-top: 2px; }}

/* ===== DETAIL ROWS ===== */

.detail-row {{
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 7px 0;
    border-bottom: 1px solid {p["border"]};
    font-size: 11px;
    color: {p["text_secondary"]};
}}

.detail-row:last-child {{
    border-bottom: none;
}}

.detail-value {{
    font-weight: 600;
    color: {p["text_primary"]};
    font-variant-numeric: tabular-nums;
}}

/* ===== HERO CARD ===== */

.hero-card {{
    background: {hero_gradient};
    border: {hero_border};
    border-radius: 12px;
    padding: 24px;
    text-align: center;
}}

.hero-card-label {{
    font-size: 10px;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 0.08em;
    color: {"rgba(255,255,255,0.8)" if not is_dark else p["text_tertiary"]};
    margin-bottom: 6px;
}}

.hero-card-value {{
    font-size: 32px;
    font-weight: 700;
    color: {"white" if not is_dark else p["brand"]};
    font-variant-numeric: tabular-nums;
    margin-bottom: 6px;
}}

.hero-card-sub {{
    font-size: 11px;
    color: {"rgba(255,255,255,0.7)" if not is_dark else p["text_secondary"]};
}}

/* ===== NARRATIVE ===== */

.narrative {{
    font-size: 11px;
    line-height: 1.65;
    color: {p["text_secondary"]};
    margin-bottom: 4px;
}}

/* ===== CALLOUT BOX ===== */

.callout-box {{
    background: {p["brand"]}10;
    border: 1px solid {p["brand"]}30;
    border-left: 3px solid {p["brand"]};
    border-radius: 8px;
    padding: 14px 16px;
    font-size: 11px;
    color: {p["text_secondary"]};
    line-height: 1.55;
}}

.callout-box strong {{
    color: {p["text_primary"]};
}}

/* ===== ADJUSTMENT TABLE ===== */

.adj-table {{
    width: 100%;
    border-collapse: collapse;
    font-size: {"8px" if len(self.data.comp_adjustments) > 5 else "9px"};
    margin-top: 16px;
}}

.adj-table th {{
    background: {p["brand_dark"] if not is_dark else "#101828"};
    color: {"white" if not is_dark else p["text_secondary"]};
    padding: 7px 5px;
    text-align: center;
    font-size: {"7px" if len(self.data.comp_adjustments) > 5 else "8px"};
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 0.04em;
}}

.adj-table th:first-child,
.row-label-header {{
    text-align: left;
    min-width: 70px;
}}

.adj-table td {{
    padding: 5px;
    border-bottom: 1px solid {p["border"]};
    font-variant-numeric: tabular-nums;
    color: {p["text_primary"]};
    text-align: center;
}}

.adj-table tr:nth-child(even) {{
    background: {p["card_bg"]};
}}

.row-label {{
    text-align: left !important;
    font-weight: 600;
    color: {p["text_secondary"]};
    white-space: nowrap;
}}

.adj-label {{
    padding-left: 12px !important;
    font-weight: 500 !important;
}}

.adj-header td {{
    background: {p["brand"]}10;
    font-weight: 700 !important;
    color: {p["brand"]} !important;
    text-transform: uppercase;
    letter-spacing: 0.04em;
    font-size: 8px;
    padding: 6px 5px;
    border-top: 2px solid {p["brand"]}40;
}}

.total-row td {{
    border-top: 2px solid {p["border"]};
    font-weight: 700;
}}

td.money {{
    font-weight: 600;
    font-variant-numeric: tabular-nums;
}}

/* ===== SUMMARY TABLE ===== */

.summary-table {{
    width: 100%;
    border-collapse: collapse;
    font-size: 9px;
}}

.summary-table th {{
    background: {p["brand_dark"] if not is_dark else "#101828"};
    color: {"white" if not is_dark else p["text_secondary"]};
    padding: 8px 6px;
    text-align: left;
    font-size: 9px;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 0.04em;
}}

.summary-table td {{
    padding: 6px;
    border-bottom: 1px solid {p["border"]};
    font-variant-numeric: tabular-nums;
    color: {p["text_primary"]};
}}

.summary-table tr:nth-child(even) {{
    background: {p["card_bg"]};
}}

/* ===== CONFIDENCE RING ===== */

.conf-ring {{
    width: 56px;
    height: 56px;
    border-radius: 50%;
    border: 4px solid {p["brand"]};
    display: flex;
    align-items: center;
    justify-content: center;
    background: {p["bg"]};
}}

.conf-ring-value {{
    font-size: 14px;
    font-weight: 700;
    color: {p["brand"]};
}}

/* ===== DISCLAIMER ===== */

.disclaimer {{
    margin-top: 24px;
    padding: 16px;
    background: {p["card_bg"]};
    border: 1px solid {p["border"]};
    border-radius: 8px;
    font-size: 9px;
    color: {p["text_tertiary"]};
    line-height: 1.6;
}}

.disclaimer strong {{
    color: {p["text_secondary"]};
}}

.final-footer {{
    margin-top: 24px;
    text-align: center;
}}

.final-footer .footer-date {{
    margin-top: 6px;
}}
"""
