"""Cash buyer directory data and access helpers."""

from __future__ import annotations

from typing import TypedDict


class BuyerRecord(TypedDict):
    id: int
    initials: str
    accent: str
    company: str
    owner: str
    street: str
    city: str
    state: str
    zip: str
    phone: str
    email: str
    website: str
    coverage: list[str]
    description: str
    deals: int
    years: int
    response: str
    strategies: list[str]


BUYERS: list[BuyerRecord] = [
    {
        "id": 1,
        "initials": "DD",
        "accent": "#0EA5E9",
        "company": "Revival Home Buyer",
        "owner": "Daniel Di Bartolomeo",
        "street": "4830 W Kennedy Blvd, Suite 600",
        "city": "Tampa",
        "state": "FL",
        "zip": "33609",
        "phone": "(813) 548-3674",
        "email": "info@revivalhomebuyer.com",
        "website": "revivalhomebuyer.com",
        "coverage": ["Hillsborough", "Pinellas", "Pasco", "Polk", "Manatee"],
        "description": "Family-run fix-and-flip operator serving Tampa Bay since 2017. Closes in 7-14 days, buys properties in any condition including hoarder homes and code violations.",
        "deals": 184,
        "years": 8,
        "response": "< 24h",
        "strategies": ["Fix & Flip", "BRRRR"],
    },
    {
        "id": 2,
        "initials": "OR",
        "accent": "#A78BFA",
        "company": "Florida Cash Home Buyers",
        "owner": "Omer Reiner",
        "street": "1925 NW 35th St",
        "city": "Miami",
        "state": "FL",
        "zip": "33142",
        "phone": "(954) 519-7040",
        "email": "omer@floridacashhomebuyers.com",
        "website": "floridacashhomebuyers.com",
        "coverage": ["Miami-Dade", "Broward", "Palm Beach", "Hillsborough", "Orange", "Duval"],
        "description": "Statewide buyer with 15+ years in Florida. Specializes in distressed inheritances, divorce sales, and pre-foreclosure properties.",
        "deals": 412,
        "years": 15,
        "response": "< 12h",
        "strategies": ["Fix & Flip", "Buy & Hold", "Wholesale"],
    },
    {
        "id": 3,
        "initials": "RC",
        "accent": "#0EA5E9",
        "company": "Hello Reeve",
        "owner": "Reeve Conyngham",
        "street": "1700 N Federal Hwy",
        "city": "Boca Raton",
        "state": "FL",
        "zip": "33432",
        "phone": "(561) 220-1212",
        "email": "reeve@helloreeve.com",
        "website": "helloreeve.com",
        "coverage": ["Palm Beach", "Broward", "Martin", "St. Lucie"],
        "description": "Solo operator focused on luxury distressed and probate properties on the Treasure Coast. Direct decision-maker, no middlemen.",
        "deals": 67,
        "years": 6,
        "response": "< 6h",
        "strategies": ["Fix & Flip"],
    },
    {
        "id": 4,
        "initials": "MT",
        "accent": "#FACC15",
        "company": "Liberty House Buying Group",
        "owner": "Marcus Thompson",
        "street": "2870 Peachtree Rd NW #501",
        "city": "Jacksonville",
        "state": "FL",
        "zip": "32202",
        "phone": "(904) 580-2244",
        "email": "deals@libertyhousebuyinggroup.com",
        "website": "libertyhousebuyinggroup.com",
        "coverage": ["Duval", "St. Johns", "Clay", "Nassau"],
        "description": "North Florida specialist. Buys 8-12 properties per month across Jacksonville metro. Wholesaler-friendly with assignable contracts.",
        "deals": 138,
        "years": 9,
        "response": "< 24h",
        "strategies": ["Fix & Flip", "Wholesale", "Buy & Hold"],
    },
    {
        "id": 5,
        "initials": "CM",
        "accent": "#0EA5E9",
        "company": "Cornerstone Home Buyers",
        "owner": "Linda & Carlos Mendez",
        "street": "500 W Cypress Creek Rd",
        "city": "Fort Lauderdale",
        "state": "FL",
        "zip": "33309",
        "phone": "(954) 633-7195",
        "email": "offers@cornerstonehomebuyers.com",
        "website": "cornerstonehomebuyers.com",
        "coverage": ["Broward", "Miami-Dade"],
        "description": "Husband-wife team with construction background. Tackles heavy rehabs others pass on — fire damage, foundation issues, full gut jobs.",
        "deals": 92,
        "years": 7,
        "response": "< 24h",
        "strategies": ["Fix & Flip"],
    },
    {
        "id": 6,
        "initials": "BL",
        "accent": "#A78BFA",
        "company": "Sell To Bobby",
        "owner": "Bobby Larsen",
        "street": "4040 Sheridan St",
        "city": "Hollywood",
        "state": "FL",
        "zip": "33021",
        "phone": "(954) 248-9928",
        "email": "bobby@selltobobby.com",
        "website": "selltobobby.com",
        "coverage": ["Broward", "Miami-Dade", "Palm Beach"],
        "description": "Independent investor since 2013. Personally inspects every property. Strong reputation in South Florida wholesale community.",
        "deals": 76,
        "years": 12,
        "response": "< 12h",
        "strategies": ["Fix & Flip", "Buy & Hold"],
    },
    {
        "id": 7,
        "initials": "JP",
        "accent": "#0EA5E9",
        "company": "Central Florida House Buyers",
        "owner": "Jason Patel",
        "street": "801 N Magnolia Ave",
        "city": "Orlando",
        "state": "FL",
        "zip": "32803",
        "phone": "(407) 535-0202",
        "email": "jason@cfhousebuyers.com",
        "website": "cfhousebuyers.com",
        "coverage": ["Orange", "Seminole", "Osceola", "Lake", "Volusia"],
        "description": "Orlando metro fix-and-flipper with strong contractor crew. Targets 1980s-2000s suburban properties needing cosmetic-to-medium rehabs.",
        "deals": 156,
        "years": 10,
        "response": "< 24h",
        "strategies": ["Fix & Flip", "BRRRR"],
    },
    {
        "id": 8,
        "initials": "SW",
        "accent": "#FACC15",
        "company": "Optimal Home Buyers",
        "owner": "Sarah Whitmore",
        "street": "1700 W Hibiscus Blvd",
        "city": "Melbourne",
        "state": "FL",
        "zip": "32901",
        "phone": "(321) 209-1551",
        "email": "sarah@optimalhomebuyers.net",
        "website": "optimalhomebuyers.net",
        "coverage": ["Brevard", "Indian River", "Orange"],
        "description": "Space Coast specialist. Buys mobile homes, condos, and SFR. Cash within 7 days, handles existing tenant situations.",
        "deals": 58,
        "years": 5,
        "response": "< 24h",
        "strategies": ["Buy & Hold", "Fix & Flip"],
    },
    {
        "id": 9,
        "initials": "EV",
        "accent": "#0EA5E9",
        "company": "Priority Home Buyers",
        "owner": "Eric Vance",
        "street": "601 N Ashley Dr",
        "city": "Tampa",
        "state": "FL",
        "zip": "33602",
        "phone": "(727) 287-8888",
        "email": "eric@priorityhomebuyers.com",
        "website": "priorityhomebuyers.com",
        "coverage": ["Hillsborough", "Pinellas", "Pasco"],
        "description": "Tampa Bay operator focused on quick-close situations. Probate, divorce, relocations. Looks at every deal within 24 hours.",
        "deals": 103,
        "years": 8,
        "response": "< 6h",
        "strategies": ["Fix & Flip", "Wholesale"],
    },
    {
        "id": 10,
        "initials": "DG",
        "accent": "#A78BFA",
        "company": "South Florida Cash Home Buyers",
        "owner": "David Goldman",
        "street": "633 NE 167th St #911",
        "city": "North Miami Beach",
        "state": "FL",
        "zip": "33162",
        "phone": "(305) 985-3134",
        "email": "david@southfloridacashhomebuyers.com",
        "website": "southfloridacashhomebuyers.com",
        "coverage": ["Miami-Dade", "Broward"],
        "description": "Tri-county buyer with deep contractor network. Strong in oceanfront and older Miami neighborhoods. Handles title issues and liens in-house.",
        "deals": 119,
        "years": 11,
        "response": "< 12h",
        "strategies": ["Fix & Flip", "BRRRR", "Buy & Hold"],
    },
]


def list_buyers() -> list[BuyerRecord]:
    """Return all paid buyer records."""
    return BUYERS
