"""
Pydantic schemas for API request/response validation.
Organized by domain for better maintainability.
"""

# Re-export ALL existing schemas from property.py for backward compatibility
# New auth schemas
from app.schemas.auth import (
    AuthMessage,
    EmailVerification,
    PasswordChange,
    PasswordReset,
    PasswordResetConfirm,
    RefreshTokenRequest,
    TokenPayload,
    TokenResponse,
    UserLogin,
    UserRegister,
)

# Deal Maker schemas - central analysis data structure
from app.schemas.deal_maker import (
    CachedMetrics,
    DealMakerRecord,
    DealMakerRecordCreate,
    DealMakerRecordUpdate,
    DealMakerResponse,
    InitialAssumptions,
)
from app.schemas.property import (
    # Property Data
    Address,
    AllAssumptions,
    AnalyticsRequest,
    AnalyticsResponse,
    BRRRRAssumptions,
    BRRRRResults,
    Confidence,
    DataQuality,
    DataSource,
    ExportRequest,
    ExportResponse,
    # Provenance
    FieldProvenance,
    # Assumptions
    FinancingAssumptions,
    FlipAssumptions,
    FlipResults,
    HouseHackAssumptions,
    HouseHackResults,
    ListingInfo,
    ListingStatus,
    # Calculation Results
    LTRResults,
    MarketData,
    MarketStatistics,
    MarketTemperature,
    OperatingAssumptions,
    PropertyDetails,
    PropertyResponse,
    # API Requests/Responses
    PropertySearchRequest,
    # Enums
    PropertyType,
    ProvenanceMap,
    RehabAssumptions,
    RentalData,
    RentalMarketStatistics,
    RentTrend,
    RiskLevel,
    SellerType,
    SensitivityRequest,
    SensitivityResponse,
    STRAssumptions,
    StrategyComparison,
    StrategyType,
    STRResults,
    ValuationData,
    WholesaleAssumptions,
    WholesaleResults,
)

# New saved property schemas
from app.schemas.saved_property import (
    BulkStatusUpdate,
    BulkTagUpdate,
    PropertyAdjustmentCreate,
    PropertyAdjustmentResponse,
    PropertyStatus,
    SavedPropertyCreate,
    SavedPropertyResponse,
    SavedPropertySummary,
    SavedPropertyUpdate,
)

# New user schemas
from app.schemas.user import (
    ExperienceLevel,
    OnboardingProgress,
    RiskTolerance,
    UserCreate,
    UserProfileCreate,
    UserProfileResponse,
    UserProfileUpdate,
    UserResponse,
    UserUpdate,
    UserWithProfile,
)

__all__ = [
    "Address",
    "AllAssumptions",
    "AnalyticsRequest",
    "AnalyticsResponse",
    "AuthMessage",
    "BRRRRAssumptions",
    "BRRRRResults",
    "BulkStatusUpdate",
    "BulkTagUpdate",
    "CachedMetrics",
    "Confidence",
    "DataQuality",
    "DataSource",
    "DealMakerRecord",
    "DealMakerRecordCreate",
    "DealMakerRecordUpdate",
    "DealMakerResponse",
    "EmailVerification",
    # User
    "ExperienceLevel",
    "ExportRequest",
    "ExportResponse",
    "FieldProvenance",
    "FinancingAssumptions",
    "FlipAssumptions",
    "FlipResults",
    "HouseHackAssumptions",
    "HouseHackResults",
    # Deal Maker
    "InitialAssumptions",
    "LTRResults",
    "ListingInfo",
    "ListingStatus",
    "MarketData",
    "MarketStatistics",
    "MarketTemperature",
    "OnboardingProgress",
    "OperatingAssumptions",
    "PasswordChange",
    "PasswordReset",
    "PasswordResetConfirm",
    "PropertyAdjustmentCreate",
    "PropertyAdjustmentResponse",
    "PropertyDetails",
    "PropertyResponse",
    "PropertySearchRequest",
    # Saved Properties
    "PropertyStatus",
    # Property/Analytics (backward compatible)
    "PropertyType",
    "ProvenanceMap",
    "RefreshTokenRequest",
    "RehabAssumptions",
    "RentTrend",
    "RentalData",
    "RentalMarketStatistics",
    "RiskLevel",
    "RiskTolerance",
    "STRAssumptions",
    "STRResults",
    "SavedPropertyCreate",
    "SavedPropertyResponse",
    "SavedPropertySummary",
    "SavedPropertyUpdate",
    "SellerType",
    "SensitivityRequest",
    "SensitivityResponse",
    "StrategyComparison",
    "StrategyType",
    "TokenPayload",
    "TokenResponse",
    "UserCreate",
    "UserLogin",
    "UserProfileCreate",
    "UserProfileResponse",
    "UserProfileUpdate",
    # Auth
    "UserRegister",
    "UserResponse",
    "UserUpdate",
    "UserWithProfile",
    "ValuationData",
    "WholesaleAssumptions",
    "WholesaleResults",
]
