// src/pages/BuyerDirectory.tsx
// =============================================================================
// DealGapIQ — Cash Buyer Directory (Pro members only)
// =============================================================================
//
// HOW TO ADD THIS TO THE APP:
// 1. Drop buyers.json into src/data/buyers.json
//    (generated by export_buyers.py from the IQ-Data pipeline)
// 2. Drop this file into src/pages/BuyerDirectory.tsx
// 3. In App.tsx, add the route:
//      import BuyerDirectory from './pages/BuyerDirectory';
//      <Route path="/directory" element={<BuyerDirectory />} />
// 4. In your nav, add a link: <Link to="/directory">Buyer Directory</Link>
//
// WHAT TO WIRE LATER:
//   [auth]  Replace `useState(true)` for isPro with your real auth context
//   [demo]  Remove the dev tier toggle in the top-right before shipping
//   [api]   When moving to Railway-served data, replace the static import
//           with a fetch from /api/buyers
//
// DATA SOURCE:
//   Reads from ../data/buyers.json — a static file of 2,900+ verified U.S.
//   cash buyers from the Phase 3 + Phase 4 extraction pipeline.
// =============================================================================

import { useState, useMemo, useRef, useEffect } from 'react';
import {
  Search, MapPin, Phone, Mail, Globe, Lock, CheckCircle2,
  Sparkles, Filter, Printer, FileSpreadsheet,
} from 'lucide-react';

// [data] Static buyer data — replace with fetch('/api/buyers') when backend ships
import BUYERS_DATA from '../data/buyers.json';

const BUYERS = BUYERS_DATA;

// Derive state list from actual data, sorted alphabetically
const STATES = Array.from(
  new Set(BUYERS.map((b) => b.state).filter(Boolean))
).sort();

const STRATEGIES = ['all', 'Fix & Flip', 'BRRRR', 'Buy & Hold', 'Wholesale'];

// Page size for the result grid — keeps render fast on a 2,900-buyer dataset
const PAGE_SIZE = 60;

// CSV helpers — RFC 4180 escaping
function csvField(v) {
  const s = String(v == null ? '' : v);
  return /[",\n\r]/.test(s) ? '"' + s.replace(/"/g, '""') + '"' : s;
}

// =============================================================================
// MAIN COMPONENT
// =============================================================================

export default function BuyerDirectory() {
  // [auth] TODO: replace with real auth context — useAuth().isPro or similar
  const [isPro, setIsPro] = useState(true);

  const [searchMode, setSearchMode] = useState('city');
  const [city, setCity] = useState('');
  const [stateCode, setStateCode] = useState(STATES[0] || 'FL');
  const [county, setCounty] = useState('');
  const [zip, setZip] = useState('');
  const [strategyFilter, setStrategyFilter] = useState('all');
  const [selected, setSelected] = useState(new Set());
  const [toast, setToast] = useState(null);
  const [visibleCount, setVisibleCount] = useState(PAGE_SIZE);
  const printAreaRef = useRef(null);

  const filtered = useMemo(() => {
    return BUYERS.filter((b) => {
      if (strategyFilter !== 'all' && !b.strategies.includes(strategyFilter)) return false;
      if (searchMode === 'city') {
        const q = city.toLowerCase().trim();
        if (q) {
          const matchesCity = b.city && b.city.toLowerCase().includes(q);
          const matchesCoverage = b.coverage.some((c) => c.toLowerCase().includes(q));
          if (!matchesCity && !matchesCoverage) return false;
        }
        if (stateCode && b.state !== stateCode) return false;
      } else if (searchMode === 'county') {
        const q = county.toLowerCase().trim();
        if (q && !b.coverage.some((c) => c.toLowerCase().includes(q))) return false;
      } else if (searchMode === 'zip') {
        if (zip && !b.zip.startsWith(zip)) return false;
      }
      return true;
    });
  }, [city, stateCode, county, zip, searchMode, strategyFilter]);

  // Reset visible count when filter changes
  useEffect(() => setVisibleCount(PAGE_SIZE), [city, stateCode, county, zip, searchMode, strategyFilter]);

  const visible = useMemo(() => filtered.slice(0, visibleCount), [filtered, visibleCount]);
  const selectedBuyers = BUYERS.filter((b) => selected.has(b.id));

  const toggleSelect = (id) => {
    const next = new Set(selected);
    if (next.has(id)) next.delete(id);
    else next.add(id);
    setSelected(next);
  };

  const selectAllFiltered = () => {
    const allSelected = filtered.length > 0 && filtered.every((b) => selected.has(b.id));
    const next = new Set(selected);
    if (allSelected) filtered.forEach((b) => next.delete(b.id));
    else filtered.forEach((b) => next.add(b.id));
    setSelected(next);
  };

  const clearSelected = () => setSelected(new Set());

  const showToast = (msg) => {
    setToast(msg);
    setTimeout(() => setToast(null), 2400);
  };

  const downloadCSV = () => {
    if (selectedBuyers.length === 0) return;
    const headers = ['Company', 'Owner', 'Street', 'City', 'State', 'Zip', 'Phone', 'Email', 'Website',
      'Strategies', 'Coverage', 'Years Active', 'Deals (12mo)', 'Response Time', 'Description'];
    const lines = [headers.map(csvField).join(',')];
    selectedBuyers.forEach((b) => {
      lines.push([b.company, b.owner, b.street, b.city, b.state, b.zip, b.phone, b.email, b.website,
        b.strategies.join('; '), b.coverage.join('; '), b.years, b.deals, b.response, b.description]
        .map(csvField).join(','));
    });
    const blob = new Blob([lines.join('\r\n')], { type: 'text/csv;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    const date = new Date().toISOString().split('T')[0];
    a.href = url;
    a.download = `dealgapiq-cash-buyers-${date}.csv`;
    document.body.appendChild(a);
    a.click();
    setTimeout(() => { URL.revokeObjectURL(url); a.remove(); }, 100);
    showToast(`${selectedBuyers.length} buyer${selectedBuyers.length > 1 ? 's' : ''} exported`);
  };

  const printSelected = () => {
    if (selectedBuyers.length === 0 || !printAreaRef.current) return;
    const date = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
    const html = `
      <div class="print-header">
        <h2 class="print-title">DealGapIQ — Cash Buyer Directory</h2>
        <div class="print-meta">${selectedBuyers.length} ${selectedBuyers.length === 1 ? 'buyer' : 'buyers'} · Generated ${date}</div>
      </div>
      ${selectedBuyers.map((b) => `
        <div class="print-card">
          <div class="pc-head">
            <div class="pc-avatar">${b.initials}</div>
            <div class="pc-info">
              <h3>${b.company}</h3>
              <p>${b.owner || 'Verified cash buyer'} · ${b.city || ''}${b.state ? ', ' + b.state : ''}</p>
            </div>
          </div>
          ${b.description ? `<div class="pc-desc">${b.description}</div>` : ''}
          <div class="pc-stats">
            <div class="pc-stat"><div class="l">Deals/yr</div><div class="v">${b.deals || '—'}</div></div>
            <div class="pc-stat"><div class="l">Years Active</div><div class="v">${b.years || '—'}</div></div>
            <div class="pc-stat"><div class="l">Response</div><div class="v">${b.response || '—'}</div></div>
            <div class="pc-stat"><div class="l">Strategies</div><div class="v" style="font-size:11px;font-weight:600">${b.strategies.join(', ')}</div></div>
          </div>
          ${b.street ? `<div class="pc-row"><strong>Address:</strong> ${b.street}${b.city ? ', ' + b.city : ''}${b.state ? ', ' + b.state : ''} ${b.zip || ''}</div>` : ''}
          ${b.phone ? `<div class="pc-row"><strong>Phone:</strong> ${b.phone}</div>` : ''}
          ${b.email ? `<div class="pc-row"><strong>Email:</strong> ${b.email}</div>` : ''}
          ${b.website ? `<div class="pc-row"><strong>Website:</strong> ${b.website}</div>` : ''}
          <div class="pc-row"><strong>Coverage:</strong> ${b.coverage.join(', ')}</div>
        </div>
      `).join('')}
      <div class="print-footer">DealGapIQ · See Every Property Through an Investor Lens · dealgapiq.com</div>
    `;
    printAreaRef.current.innerHTML = html;
    setTimeout(() => {
      window.print();
      setTimeout(() => { if (printAreaRef.current) printAreaRef.current.innerHTML = ''; }, 500);
    }, 50);
  };

  return (
    <div style={styles.page}>
      <style>{`
        @keyframes dgiq-toast-in { from { opacity: 0; transform: translateX(-50%) translateY(-12px); } to { opacity: 1; transform: translateX(-50%) translateY(0); } }
        .dgiq-card { transition: border-color 0.2s, box-shadow 0.2s; }
        .dgiq-card:hover { border-color: #4b5563; }
        .dgiq-card.selected { border-color: #0EA5E9 !important; box-shadow: inset 0 0 0 1px #0EA5E9; }
        .dgiq-input:focus, .dgiq-select:focus { outline: none; border-color: #0EA5E9 !important; box-shadow: 0 0 0 3px rgba(14, 165, 233, 0.15); }
        .dgiq-btn-press { transition: all 0.15s ease; }
        .dgiq-btn-press:active { transform: scale(0.97); }
        @media print {
          @page { size: letter; margin: 0.5in; }
          body { background: #fff !important; }
          body * { visibility: hidden; }
          .dgiq-print-area, .dgiq-print-area * { visibility: visible; }
          .dgiq-print-area { position: absolute; left: 0; top: 0; width: 100%; background: #fff; color: #000; font-family: 'DM Sans', system-ui, sans-serif; }
          .dgiq-print-area .print-header { display: flex; justify-content: space-between; align-items: baseline; padding-bottom: 10px; border-bottom: 2px solid #0EA5E9; margin-bottom: 16px; }
          .dgiq-print-area .print-title { font: 700 16px 'DM Sans', sans-serif; color: #1B2141; margin: 0; }
          .dgiq-print-area .print-meta { font: 11px 'Space Mono', monospace; color: #555; }
          .dgiq-print-area .print-card { border: 1px solid #d1d5db; border-radius: 8px; padding: 14px; margin-bottom: 12px; background: #fff; page-break-after: always; break-after: page; page-break-inside: avoid; break-inside: avoid; }
          .dgiq-print-area .print-card:last-of-type { page-break-after: auto; break-after: auto; }
          .dgiq-print-area .pc-head { display: flex; gap: 12px; margin-bottom: 8px; }
          .dgiq-print-area .pc-avatar { width: 44px; height: 44px; border-radius: 8px; background: #0EA5E9; color: #fff; display: flex; align-items: center; justify-content: center; font: 700 14px 'DM Sans', sans-serif; flex-shrink: 0; }
          .dgiq-print-area .pc-info h3 { font: 700 14px 'DM Sans', sans-serif; color: #1B2141; margin: 0 0 2px; }
          .dgiq-print-area .pc-info p { font: 12px 'DM Sans', sans-serif; color: #555; margin: 0; }
          .dgiq-print-area .pc-desc { font: 11px 'DM Sans', sans-serif; color: #333; line-height: 1.5; margin: 8px 0; }
          .dgiq-print-area .pc-stats { display: flex; gap: 16px; padding: 8px 0; border-top: 1px solid #e5e7eb; border-bottom: 1px solid #e5e7eb; margin: 8px 0; }
          .dgiq-print-area .pc-stat { flex: 1; }
          .dgiq-print-area .pc-stat .l { font: 8px 'DM Sans', sans-serif; color: #6b7280; letter-spacing: 1px; text-transform: uppercase; margin-bottom: 2px; }
          .dgiq-print-area .pc-stat .v { font: 700 14px 'DM Sans', sans-serif; color: #1B2141; }
          .dgiq-print-area .pc-row { display: flex; gap: 16px; font: 11px 'DM Sans', sans-serif; color: #333; margin: 4px 0; }
          .dgiq-print-area .pc-row strong { color: #1B2141; min-width: 70px; display: inline-block; }
          .dgiq-print-area .print-footer { position: fixed; bottom: 0.25in; left: 0; right: 0; text-align: center; font: 9px 'Space Mono', monospace; color: #6b7280; }
        }
      `}</style>

      {/* [demo] TODO: remove this tier toggle before shipping — use real auth */}
      <div style={styles.devToggle}>
        <span style={{ fontFamily: 'Space Mono, monospace', color: '#6b7280', fontSize: 11, letterSpacing: 1 }}>DEV</span>
        <button onClick={() => setIsPro(!isPro)} style={{
          ...styles.devToggleBtn,
          background: isPro ? '#0EA5E9' : '#1f2937',
          color: isPro ? '#000' : '#fff',
        }}>
          {isPro ? 'PRO' : 'STARTER'}
        </button>
      </div>

      <div style={styles.container}>
        <div style={{ marginBottom: 32 }}>
          <div style={styles.eyebrow}>
            <div style={styles.eyebrowDot} />
            <span>DealGapIQ / Directory</span>
          </div>
          <h1 style={styles.h1}>
            Cash Buyer <span style={{ color: '#0EA5E9' }}>Directory</span>
          </h1>
          <p style={styles.sub}>
            {BUYERS.length.toLocaleString()} verified fix-and-flippers, BRRRR buyers, and active investors across every major U.S. market.
            Skip the cold outreach — search by city, county, or zip and connect direct.
          </p>
        </div>

        <div style={styles.panel}>
          <div style={styles.tabs}>
            {['city', 'county', 'zip'].map((mode) => (
              <button key={mode} onClick={() => setSearchMode(mode)} className="dgiq-btn-press" style={{
                ...styles.tab,
                background: searchMode === mode ? '#0EA5E9' : 'transparent',
                color: searchMode === mode ? '#000' : '#9ca3af',
              }}>
                {mode === 'city' ? 'City + State' : mode === 'county' ? 'County' : 'Zip Code'}
              </button>
            ))}
          </div>

          <div style={{ display: 'grid', gridTemplateColumns: '1fr auto', gap: 16, alignItems: 'end' }}>
            <div style={{ display: 'grid', gridTemplateColumns: searchMode === 'city' ? '1fr 140px' : '1fr', gap: 12 }}>
              {searchMode === 'city' && (
                <>
                  <Field label="City" icon={<MapPin size={16} />}>
                    <input className="dgiq-input" style={styles.input}
                      value={city} onChange={(e) => setCity(e.target.value)} placeholder="Tampa, Miami, Houston..." />
                  </Field>
                  <Field label="State">
                    <select className="dgiq-select" style={styles.select}
                      value={stateCode} onChange={(e) => setStateCode(e.target.value)}>
                      {STATES.map((s) => <option key={s} value={s}>{s}</option>)}
                    </select>
                  </Field>
                </>
              )}
              {searchMode === 'county' && (
                <Field label="County name" icon={<MapPin size={16} />}>
                  <input className="dgiq-input" style={styles.input}
                    value={county} onChange={(e) => setCounty(e.target.value)} placeholder="Hillsborough, Harris, Cook..." />
                </Field>
              )}
              {searchMode === 'zip' && (
                <Field label="Zip code" icon={<MapPin size={16} />}>
                  <input className="dgiq-input" style={styles.input}
                    value={zip} onChange={(e) => setZip(e.target.value)} placeholder="33602" maxLength={5} />
                </Field>
              )}
            </div>
            <button className="dgiq-btn-press" style={styles.searchBtn}>
              <Search size={16} /> Search
            </button>
          </div>

          <div style={styles.filterRow}>
            <Filter size={14} style={{ color: '#6b7280' }} />
            <span style={styles.filterLabel}>Strategy</span>
            <div style={{ display: 'flex', gap: 6, flexWrap: 'wrap' }}>
              {STRATEGIES.map((s) => (
                <button key={s} onClick={() => setStrategyFilter(s)} style={{
                  ...styles.chip,
                  background: strategyFilter === s ? 'rgba(14, 165, 233, 0.15)' : 'transparent',
                  color: strategyFilter === s ? '#0EA5E9' : '#9ca3af',
                  borderColor: strategyFilter === s ? '#0EA5E9' : '#1f2937',
                }}>
                  {s === 'all' ? 'All Strategies' : s}
                </button>
              ))}
            </div>
          </div>
        </div>

        <div style={styles.countStrip}>
          <div style={{ display: 'flex', alignItems: 'baseline', gap: 12 }}>
            <span style={styles.countNum}>{filtered.length.toLocaleString()}</span>
            <span style={{ fontSize: 14, color: '#9ca3af' }}>
              verified buyers {searchMode === 'city' && city ? `in ${city}, ${stateCode}` :
                searchMode === 'county' && county ? `in ${county} County` :
                searchMode === 'zip' && zip ? `near ${zip}` :
                searchMode === 'city' ? `in ${stateCode}` : 'nationwide'}
            </span>
          </div>
          {isPro && filtered.length > 0 && (
            <button onClick={selectAllFiltered} style={styles.selectAllBtn}>
              <CheckCircle2 size={14} />
              {filtered.length > 0 && filtered.every((b) => selected.has(b.id)) ? 'Clear all' : 'Select visible'}
            </button>
          )}
          {!isPro && (
            <div style={{ display: 'flex', alignItems: 'center', gap: 8, fontSize: 12, color: '#FACC15' }}>
              <Lock size={14} />
              <span style={{ fontFamily: 'Space Mono, monospace', letterSpacing: 0.5 }}>PRO ONLY</span>
            </div>
          )}
        </div>

        <div style={{ position: 'relative' }}>
          <div style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fill, minmax(300px, 1fr))',
            gap: 16,
            filter: isPro ? 'none' : 'blur(8px)',
            pointerEvents: isPro ? 'auto' : 'none',
            userSelect: isPro ? 'auto' : 'none',
            transition: 'filter 0.4s ease',
          }}>
            {visible.map((b) => (
              <BuyerCard key={b.id} buyer={b} selected={selected.has(b.id)} onToggle={() => toggleSelect(b.id)} />
            ))}
          </div>

          {isPro && filtered.length > visibleCount && (
            <div style={{ display: 'flex', justifyContent: 'center', marginTop: 22 }}>
              <button onClick={() => setVisibleCount((c) => c + PAGE_SIZE)} style={styles.loadMoreBtn}>
                Show {Math.min(PAGE_SIZE, filtered.length - visibleCount)} more
                <span style={{ fontFamily: 'Space Mono, monospace', color: '#6b7280', marginLeft: 6 }}>
                  · {filtered.length - visibleCount} remaining
                </span>
              </button>
            </div>
          )}

          {filtered.length === 0 && (
            <div style={styles.emptyState}>
              <Search size={28} style={{ color: '#1f2937', marginBottom: 12 }} />
              <div style={{ fontSize: 16, fontWeight: 600, color: '#9ca3af', marginBottom: 4 }}>No buyers match your search</div>
              <div style={{ fontSize: 13, color: '#6b7280' }}>Try a different city, broaden to all strategies, or search by county.</div>
            </div>
          )}

          {!isPro && (
            <div style={styles.gateWrap}>
              <div style={styles.gateCard}>
                <div style={styles.gateIcon}><Lock size={24} color="#fff" /></div>
                <div style={styles.gateEyebrow}>Pro Membership Required</div>
                <h2 style={styles.gateTitle}>Unlock {filtered.length.toLocaleString()} verified buyers</h2>
                <p style={styles.gateDesc}>
                  Full contact info, coverage areas, and direct outreach for every active cash buyer in your market.
                </p>
                <div style={{ display: 'flex', flexDirection: 'column', gap: 10, marginBottom: 24, textAlign: 'left' }}>
                  {['Phone, email, and website for every buyer',
                    `${BUYERS.length.toLocaleString()}+ verified buyers nationwide`,
                    'Coverage by county and zip code',
                    'Direct download to CSV or print to PDF'].map((item) => (
                    <div key={item} style={{ display: 'flex', alignItems: 'center', gap: 10, fontSize: 14, color: '#d1d5db' }}>
                      <CheckCircle2 size={16} style={{ color: '#0EA5E9', flexShrink: 0 }} />
                      <span>{item}</span>
                    </div>
                  ))}
                </div>
                <button onClick={() => {/* [auth] TODO: navigate to upgrade flow */}} className="dgiq-btn-press" style={styles.gateBtn}>
                  <Sparkles size={16} /> Upgrade to Pro — $29/mo
                </button>
                <div style={{ fontSize: 12, color: '#6b7280' }}>7-day free trial · Cancel anytime</div>
              </div>
            </div>
          )}
        </div>

        <div style={{
          ...styles.actionBar,
          transform: selected.size > 0 ? 'translateY(0)' : 'translateY(calc(100% + 20px))',
          opacity: selected.size > 0 ? 1 : 0,
          pointerEvents: selected.size > 0 ? 'auto' : 'none',
        }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
            <span style={styles.actionCount}>
              <CheckCircle2 size={14} /> {selected.size} selected
            </span>
            <button onClick={clearSelected} style={styles.actionClear}>Clear</button>
          </div>
          <div style={{ display: 'flex', gap: 8 }}>
            <button onClick={downloadCSV} style={styles.actionBtn}>
              <FileSpreadsheet size={14} /> Download CSV
            </button>
            <button onClick={printSelected} style={{ ...styles.actionBtn, ...styles.actionBtnPrimary }}>
              <Printer size={14} /> Print / Save as PDF
            </button>
          </div>
        </div>
      </div>

      <div ref={printAreaRef} className="dgiq-print-area" />

      {toast && (
        <div style={styles.toast}>
          <CheckCircle2 size={14} /> {toast}
        </div>
      )}
    </div>
  );
}

// =============================================================================
// SUB-COMPONENTS
// =============================================================================

function BuyerCard({ buyer, selected, onToggle }) {
  return (
    <div onClick={onToggle} className={`dgiq-card${selected ? ' selected' : ''}`} style={styles.card}>
      <div style={{
        position: 'absolute', top: 0, left: 0, right: 0, height: 2,
        background: `linear-gradient(90deg, transparent, ${buyer.accent}, transparent)`,
        opacity: 0.5,
      }} />
      <div style={{
        ...styles.checkbox,
        background: selected ? '#0EA5E9' : '#000',
        borderColor: selected ? '#0EA5E9' : '#4b5563',
      }}>
        {selected && (
          <div style={{
            width: 9, height: 5, borderLeft: '2px solid #000', borderBottom: '2px solid #000',
            transform: 'rotate(-45deg) translate(0, -1px)',
          }} />
        )}
      </div>

      <div style={{ display: 'flex', gap: 12, alignItems: 'flex-start', marginBottom: 14, paddingRight: 32 }}>
        <div style={{
          width: 44, height: 44, borderRadius: 10,
          background: `${buyer.accent}2E`, border: `1px solid ${buyer.accent}4D`,
          display: 'flex', alignItems: 'center', justifyContent: 'center',
          fontFamily: 'Space Mono, monospace', fontWeight: 700, fontSize: 13, color: buyer.accent,
          flexShrink: 0,
        }}>
          {buyer.initials}
        </div>
        <div style={{ flex: 1, minWidth: 0 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 5, marginBottom: 2 }}>
            <h3 style={{ fontSize: 15, fontWeight: 700, margin: 0, letterSpacing: '-0.01em',
              overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{buyer.company}</h3>
            <CheckCircle2 size={13} style={{ color: '#0EA5E9', flexShrink: 0 }} />
          </div>
          <div style={{ fontSize: 12, color: '#9ca3af' }}>
            {buyer.owner || `${buyer.city || ''}${buyer.city && buyer.state ? ', ' : ''}${buyer.state || ''}`.trim() || 'Verified cash buyer'}
          </div>
        </div>
      </div>

      {buyer.description && (
        <p style={styles.cardDesc}>{buyer.description}</p>
      )}

      {(buyer.deals > 0 || buyer.years > 0 || buyer.response) && (
        <div style={styles.statStrip}>
          <Stat label="Deals/yr" value={buyer.deals > 0 ? buyer.deals : '—'} />
          <Stat label="Years" value={buyer.years > 0 ? buyer.years : '—'} />
          <Stat label="Response" value={buyer.response || '—'} small />
        </div>
      )}

      <div style={{ marginBottom: 14 }}>
        <div style={styles.miniLabel}>Buys</div>
        <div style={{ display: 'flex', gap: 5, flexWrap: 'wrap' }}>
          {buyer.strategies.map((s) => (
            <span key={s} style={styles.strategyChip}>{s}</span>
          ))}
        </div>
      </div>

      <div style={{ marginBottom: 14 }}>
        <div style={styles.miniLabel}>Coverage</div>
        <div style={{ fontSize: 12, color: '#d1d5db' }}>{buyer.coverage.join(' · ')}</div>
      </div>

      <div style={{ paddingTop: 12, borderTop: '1px solid #1f2937' }}>
        {(buyer.street || buyer.city) && (
          <div style={{ display: 'flex', gap: 6, marginBottom: 8, fontSize: 12, color: '#9ca3af', lineHeight: 1.5 }}>
            <MapPin size={13} style={{ marginTop: 2, flexShrink: 0, color: '#6b7280' }} />
            <div>
              {buyer.street && <>{buyer.street}<br /></>}
              {buyer.city}{buyer.city && buyer.state ? ', ' : ''}{buyer.state} {buyer.zip}
            </div>
          </div>
        )}
        {buyer.phone && <ContactRow icon={<Phone size={12} />} value={buyer.phone} />}
        {buyer.email && <ContactRow icon={<Mail size={12} />} value={buyer.email} />}
        {buyer.website && <ContactRow icon={<Globe size={12} />} value={buyer.website} />}
      </div>
    </div>
  );
}

function Field({ label, icon, children }) {
  return (
    <div>
      <label style={styles.fieldLabel}>{label}</label>
      <div style={{ position: 'relative' }}>
        {icon && (
          <span style={{
            position: 'absolute', left: 14, top: '50%', transform: 'translateY(-50%)',
            color: '#6b7280', pointerEvents: 'none',
          }}>{icon}</span>
        )}
        {children}
      </div>
    </div>
  );
}

function Stat({ label, value, small }) {
  return (
    <div style={{ background: '#000', padding: '8px 10px', borderRadius: 7, textAlign: 'center' }}>
      <div style={{
        fontFamily: 'Space Mono, monospace', fontSize: 9, color: '#6b7280',
        letterSpacing: 0.7, textTransform: 'uppercase', marginBottom: 3,
      }}>{label}</div>
      <div style={{
        fontFamily: 'Space Mono, monospace', fontSize: small ? 12 : 14, fontWeight: 700,
        color: '#fff', letterSpacing: '-0.02em',
      }}>{value}</div>
    </div>
  );
}

function ContactRow({ icon, value }) {
  return (
    <div style={{ display: 'flex', alignItems: 'center', gap: 7, padding: '2px 0', fontSize: 12, color: '#d1d5db' }}>
      <span style={{ color: '#6b7280' }}>{icon}</span>
      <span style={{ overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{value}</span>
    </div>
  );
}

// =============================================================================
// STYLES
// =============================================================================

const styles = {
  page: { minHeight: '100vh', background: '#000', color: '#fff', fontFamily: '"DM Sans", -apple-system, BlinkMacSystemFont, sans-serif', padding: '32px 24px 100px', position: 'relative' },
  container: { maxWidth: 1280, margin: '0 auto' },
  devToggle: { position: 'fixed', top: 16, right: 16, zIndex: 100, display: 'flex', gap: 8, alignItems: 'center', background: '#0a0a0a', padding: '8px 12px', borderRadius: 8, border: '1px solid #1f2937', fontSize: 12 },
  devToggleBtn: { border: 'none', padding: '6px 14px', borderRadius: 6, cursor: 'pointer', fontFamily: 'inherit', fontWeight: 600, fontSize: 11, letterSpacing: 0.5 },
  eyebrow: { display: 'inline-flex', alignItems: 'center', gap: 8, marginBottom: 14, fontSize: 11, color: '#0EA5E9', letterSpacing: 2, textTransform: 'uppercase', fontFamily: 'Space Mono, monospace' },
  eyebrowDot: { width: 6, height: 6, borderRadius: '50%', background: '#0EA5E9', boxShadow: '0 0 12px #0EA5E9' },
  h1: { fontSize: 'clamp(36px, 5vw, 52px)', fontWeight: 700, lineHeight: 1.05, margin: '0 0 14px', letterSpacing: '-0.02em' },
  sub: { fontSize: 17, color: '#9ca3af', maxWidth: 640, lineHeight: 1.5, margin: 0 },
  panel: { background: 'linear-gradient(180deg, #0a0a0a 0%, #050505 100%)', border: '1px solid #1f2937', borderRadius: 14, padding: 20, marginBottom: 20 },
  tabs: { display: 'inline-flex', gap: 4, marginBottom: 18, padding: 4, background: '#000', borderRadius: 10, border: '1px solid #1f2937' },
  tab: { border: 'none', padding: '8px 16px', borderRadius: 6, cursor: 'pointer', fontFamily: 'inherit', fontWeight: 600, fontSize: 13, transition: 'all 0.2s' },
  fieldLabel: { display: 'block', fontFamily: 'Space Mono, monospace', fontSize: 10, color: '#6b7280', letterSpacing: 1.4, textTransform: 'uppercase', marginBottom: 7 },
  input: { width: '100%', background: '#000', color: '#fff', border: '1px solid #1f2937', borderRadius: 9, padding: '12px 14px 12px 42px', fontFamily: 'inherit', fontSize: 14, boxSizing: 'border-box', transition: 'all 0.2s' },
  select: { width: '100%', background: '#000', color: '#fff', border: '1px solid #1f2937', borderRadius: 9, padding: '12px 14px', fontFamily: 'inherit', fontSize: 14, fontWeight: 600, cursor: 'pointer', appearance: 'none', backgroundImage: `url("data:image/svg+xml,%3Csvg width='10' height='6' viewBox='0 0 10 6' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M1 1l4 4 4-4' stroke='%236b7280' stroke-width='1.5' fill='none' stroke-linecap='round'/%3E%3C/svg%3E")`, backgroundRepeat: 'no-repeat', backgroundPosition: 'right 14px center' },
  searchBtn: { background: '#0EA5E9', color: '#000', border: 'none', padding: '12px 24px', borderRadius: 9, cursor: 'pointer', fontFamily: 'inherit', fontWeight: 700, fontSize: 14, letterSpacing: 0.3, display: 'flex', alignItems: 'center', gap: 8 },
  filterRow: { display: 'flex', alignItems: 'center', gap: 12, marginTop: 18, paddingTop: 18, borderTop: '1px solid #1f2937' },
  filterLabel: { fontFamily: 'Space Mono, monospace', fontSize: 11, color: '#6b7280', letterSpacing: 1, textTransform: 'uppercase' },
  chip: { border: '1px solid', padding: '5px 12px', borderRadius: 999, cursor: 'pointer', fontFamily: 'inherit', fontSize: 12, fontWeight: 500, transition: 'all 0.2s' },
  countStrip: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 18, padding: '0 4px' },
  countNum: { fontFamily: 'Space Mono, monospace', fontSize: 30, fontWeight: 700, color: '#0EA5E9' },
  selectAllBtn: { background: 'transparent', color: '#0EA5E9', border: '1px solid rgba(14, 165, 233, 0.3)', padding: '6px 12px', borderRadius: 7, cursor: 'pointer', fontFamily: 'inherit', fontSize: 12, fontWeight: 600, display: 'inline-flex', alignItems: 'center', gap: 6 },
  loadMoreBtn: { background: 'transparent', color: '#0EA5E9', border: '1px solid rgba(14, 165, 233, 0.3)', padding: '10px 22px', borderRadius: 9, cursor: 'pointer', fontFamily: 'inherit', fontSize: 13, fontWeight: 600 },
  card: { background: 'linear-gradient(180deg, #0a0a0a 0%, #050505 100%)', border: '1px solid #1f2937', borderRadius: 14, padding: 18, position: 'relative', overflow: 'hidden', cursor: 'pointer' },
  checkbox: { position: 'absolute', top: 14, right: 14, width: 22, height: 22, border: '1.5px solid', borderRadius: 5, display: 'flex', alignItems: 'center', justifyContent: 'center', transition: 'all 0.15s' },
  cardDesc: { fontSize: 13, color: '#d1d5db', lineHeight: 1.55, margin: '0 0 14px' },
  statStrip: { display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 1, background: '#1f2937', borderRadius: 8, padding: 1, marginBottom: 14 },
  miniLabel: { fontFamily: 'Space Mono, monospace', fontSize: 9, color: '#6b7280', letterSpacing: 1.2, textTransform: 'uppercase', marginBottom: 6 },
  strategyChip: { background: 'rgba(14, 165, 233, 0.1)', color: '#0EA5E9', padding: '2px 9px', borderRadius: 999, fontSize: 11, fontWeight: 600, border: '1px solid rgba(14, 165, 233, 0.22)' },
  emptyState: { padding: '60px 20px', textAlign: 'center', border: '1px dashed #1f2937', borderRadius: 14 },
  gateWrap: { position: 'absolute', inset: 0, display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 32, pointerEvents: 'auto' },
  gateCard: { maxWidth: 480, width: '100%', background: 'linear-gradient(180deg, #0a0a0a 0%, #000 100%)', border: '1px solid rgba(14, 165, 233, 0.4)', borderRadius: 18, padding: 32, boxShadow: '0 24px 80px rgba(0,0,0,0.8), 0 0 60px rgba(14, 165, 233, 0.2)', textAlign: 'center' },
  gateIcon: { width: 52, height: 52, borderRadius: 13, margin: '0 auto 16px', background: 'linear-gradient(135deg, #0EA5E9 0%, #1B2141 100%)', display: 'flex', alignItems: 'center', justifyContent: 'center', boxShadow: '0 0 32px rgba(14, 165, 233, 0.4)' },
  gateEyebrow: { fontFamily: 'Space Mono, monospace', fontSize: 11, color: '#0EA5E9', letterSpacing: 2, textTransform: 'uppercase', marginBottom: 8 },
  gateTitle: { fontSize: 24, fontWeight: 700, margin: '0 0 12px', letterSpacing: '-0.01em' },
  gateDesc: { fontSize: 14, color: '#9ca3af', lineHeight: 1.55, margin: '0 0 22px' },
  gateBtn: { width: '100%', background: '#0EA5E9', color: '#000', border: 'none', padding: '13px 24px', borderRadius: 10, cursor: 'pointer', fontFamily: 'inherit', fontWeight: 700, fontSize: 14, display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 8, marginBottom: 10 },
  actionBar: { position: 'fixed', bottom: 20, left: '50%', transform: 'translateX(-50%)', width: 'calc(100% - 48px)', maxWidth: 720, background: 'linear-gradient(180deg, #0a0a0a 0%, #000 100%)', border: '1px solid #0EA5E9', borderRadius: 12, padding: '12px 16px', display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 14, flexWrap: 'wrap', boxShadow: '0 12px 40px rgba(0,0,0,0.7), 0 0 40px rgba(14, 165, 233, 0.15)', transition: 'transform 0.25s, opacity 0.25s', zIndex: 50 },
  actionCount: { fontFamily: 'inherit', fontWeight: 700, fontSize: 13, color: '#0EA5E9', display: 'inline-flex', alignItems: 'center', gap: 6 },
  actionClear: { background: 'transparent', color: '#9ca3af', border: 'none', cursor: 'pointer', fontFamily: 'inherit', fontSize: 12, padding: '4px 8px', borderRadius: 5 },
  actionBtn: { background: 'transparent', color: '#fff', border: '1px solid #1f2937', borderRadius: 8, padding: '9px 14px', cursor: 'pointer', fontFamily: 'inherit', fontWeight: 600, fontSize: 12, display: 'inline-flex', alignItems: 'center', gap: 6 },
  actionBtnPrimary: { background: '#0EA5E9', color: '#000', borderColor: '#0EA5E9' },
  toast: { position: 'fixed', top: 16, left: '50%', transform: 'translateX(-50%)', background: '#0a0a0a', border: '1px solid #22c55e', color: '#22c55e', padding: '10px 18px', borderRadius: 9, fontFamily: 'inherit', fontWeight: 600, fontSize: 13, display: 'inline-flex', alignItems: 'center', gap: 7, zIndex: 200, animation: 'dgiq-toast-in 0.25s ease' },
};
