# Generated by Django 6.0.2 on 2026-02-10 06:05

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssumptionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Assumption categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FormulaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Formula categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DefaultAssumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('value', models.TextField(default='')),
                ('description', models.TextField(blank=True)),
                ('data_type', models.CharField(choices=[('number', 'Number'), ('percentage', 'Percentage'), ('boolean', 'Boolean'), ('string', 'String'), ('currency', 'Currency')], default='number', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assumptions', to='assumptions.assumptioncategory')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_assumptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'key'],
                'unique_together': {('category', 'key')},
            },
        ),
        migrations.CreateModel(
            name='AssumptionAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('change_reason', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assumption_changes', to=settings.AUTH_USER_MODEL)),
                ('assumption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='assumptions.defaultassumption')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FormulaGlossary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('abbreviation', models.CharField(blank=True, max_length=20)),
                ('definition', models.TextField()),
                ('formula_expression', models.TextField(blank=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), blank=True, default=list, help_text='Tags for search and related formulas')),
                ('complexity', models.CharField(choices=[('simple', 'Simple'), ('moderate', 'Moderate'), ('advanced', 'Advanced')], default='moderate', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulas', to='assumptions.formulacategory')),
                ('related_assumptions', models.ManyToManyField(blank=True, help_text='Assumptions used in this formula', related_name='formulas', to='assumptions.defaultassumption')),
            ],
            options={
                'verbose_name_plural': 'Formula glossary',
                'ordering': ['category', 'name'],
            },
        ),
    ]
